name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: irislobato
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23c084fc&color_dots=%2316111a,%235b214f,%23a0447b,%23e878b1,%23ffc4df
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23c084fc&color_dots=%2316111a,%235b214f,%23a0447b,%23e878b1,%23ffc4df

      - name: Deploy snake
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
